name: Install
on:
  - push
  - pull_request
jobs:
  installer:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3 # Récupère le contenu du dépôt correspondant au commit du workflow en cours
      - name: Set up Maven #expliciter d'avoir 3.9.0
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.9.0
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' 
          java-version: '17.0.6'
      - run: mvn test #fait validate et compile
      - run: mvn verify #fait test + package

      - if: contains(github.ref, 'refs/tags/v')
        run : gh release create --generate-notes target/menu-server.jar
